Seed2/project/SystemConsoler/Controllers/RoleController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using SystemConsoler.BLL;
using Microsoft.AspNet.Identity.EntityFramework;
using SystemConsoler.BLL.Context;
using Microsoft.AspNet.Identity;
using SystemConsoler.BLL.Models;
using SystemConsoler.CustomFilters;

namespace A11_RBS.Controllers
{
    public class RoleController : Controller
    {
        ConsolerContext context;

        public RoleController()
        {
            context = new ConsolerContext();
        }



        /// <summary>
        /// Get All Roles
        /// </summary>
        /// <returns></returns>
        [AuthLog(Roles = "Salesman")]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        /// <summary>
        /// Create  a New role
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary>
        /// Create a New Role
        /// </summary>
        /// <param name="Role"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(ConvertAspNetRoleToApplicationRoleDTO(Role));
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        private Role ConvertAspNetRoleToApplicationRoleDTO(IdentityRole aspRole)
        {
            return new Role
            {

                Name = aspRole.Name
            };
        }

    }
}

Seed2/project/SystemConsoler/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}
<div style="padding:10px;height:200px" class="box box-danger">
    <h1>Create</h1>



    @using (Html.BeginForm())
    {
        <label class="c">Enter Role Name:</label>
        <div>
            @Html.EditorFor(x=> x.Name,
     new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <br />
        <input type="submit" class="btn btn-primary pull-right" value="Create Role" />
    }
</div>

Seed2/project/SystemConsoler/Views/Role/Index.cshtml
@model IEnumerable<SystemConsoler.BLL.Context.Role>
    @{
    ViewBag.Title = "Index";
    }
<div style="padding:10px"class="box box-danger">
    <h1>Roles</h1>

    @Html.ActionLink("Create Role", "Create", "Role",new { @class="btn btn-danger" })

    @*<style type="text/css">
            #tbrole, .c {
                border: double;
            }
        </style>*@

    <table id="" class="table table-striped">
        <thead>
            <tr>
                <th class="c">
                    Role Name
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="c">
                        @item.Name
                    </td>
                </tr>
            }</tbody>
</table>
</div>